version: "4.17"

services:
  client:
    image: node:16-alpine
    ports:
      - "5173:5173"
    volumes:
      - "./client:/app/client"
    working_dir: /app/client
    command: sh -c "cd /app/client; npm install; npm run dev -- --host"

  server:
    image: maven
    ports:
      - "8080:8080"
    volumes:
      - "./server:/app/server"
    working_dir: /app/server
    command: sh -c "cd /app/server; mvn spring-boot:run"